#!/usr/bin/env bash

echo Generating version.ts

COMMIT=`git rev-parse --short HEAD`
BRANCH=`git rev-parse --abbrev-ref HEAD`
# https://stackoverflow.com/a/3879077 -- how to check for uncommitted changes in git
UNTRACKED_MARK=`git diff-index --quiet HEAD -- || echo +`

cat > src/environments/version.ts << EOF
// this file is automatically generated by git-version.sh
export const version = {
  commit: '$COMMIT',
  branch: '$BRANCH',
  untrackedMark: '$UNTRACKED_MARK'
};
EOF

# todo check if uncommitted changes
